platform :ios, '12.0'

flutter_application_path = '../.ios/Flutter'
load File.join(flutter_application_path, 'Flutter.podspec')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_pods_script
end
